/*MN3D*/(function(){const SC=()=>window.QScene||window.KScene;
const $=id=>document.getElementById(id);
const wrap=$('k3dWrap'),bar=$('k3dBar');if(!wrap||!bar)return;
const st=document.createElement('style');st.textContent='#k3dMn{position:absolute;right:10px;top:54px;width:min(380px,46%);max-height:calc(100% - 120px);display:none;flex-direction:column;background:rgba(10,18,28,.92);border:1px solid #2d4256;border-radius:10px;color:#dbe8f5;font:12px Segoe UI,Arial;backdrop-filter:blur(5px);z-index:6;overflow:hidden}#k3dMn.on{display:flex}#k3dMn.big{width:min(760px,70%)}#k3dMn .h{display:flex;justify-content:space-between;align-items:center;padding:6px 8px 6px 10px;border-bottom:1px solid #2d4256;font-weight:700}#k3dMn .h button{width:auto;background:transparent;color:#cfe3f5;border:1px solid #2d4256;border-radius:6px;padding:1px 8px;margin-left:4px;cursor:pointer;font-size:13px}#k3dMn .h button:hover{border-color:#2dd4bf}#k3dMnL{display:flex;flex-wrap:wrap;gap:4px;padding:6px 8px;border-bottom:1px solid #22344a}#k3dMnL button{width:auto;display:flex;align-items:center;gap:5px;background:rgba(20,34,50,.9);color:#e3eef9;border:1px solid #2d4256;border-radius:14px;padding:2px 9px 2px 3px;font:600 11px Segoe UI,Arial;cursor:pointer}#k3dMnL button:hover{border-color:#2dd4bf}#k3dMnL b{display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#2dd4bf;color:#04121a;font-size:11px}#k3dMnS{overflow:auto;padding:6px}#k3dMnS svg{display:block;width:100%!important;height:auto!important;min-width:0!important;border-radius:6px}#k3dMn .n{padding:4px 10px 7px;color:#8ea0b4}';document.head.appendChild(st);
const b=document.createElement('button');b.id='k3dMnB';b.textContent='Mnemosxema';b.title='Jonli mnemosxema oynasi va raqamli belgilar (1, 2, 3…) — raqamni bossangiz kamera shu aparatga uchadi';bar.insertBefore(b,$('k3dQ'));
const p=document.createElement('div');p.id='k3dMn';p.innerHTML='<div class="h"><span>Mnemosxema — jonli</span><span><button id="k3dMnZ" title="Kattalashtirish">⤢</button><button id="k3dMnX" title="Yopish">×</button></span></div><div id="k3dMnL"></div><div id="k3dMnS"></div><div class="n">Raqamlar 3D’dagi aparat belgilariga mos. Bosing — kamera o‘sha joyga o‘tadi.</div>';wrap.appendChild(p);
let open=false,built=false,timer=null;
function build(){if(built||!SC()||!SC().steps)return;built=true;const L=$('k3dMnL');SC().steps.forEach(s=>{const e=document.createElement('button');e.innerHTML='<b>'+s.n+'</b>'+s.t;e.addEventListener('click',()=>SC().setView(s.v));L.appendChild(e)})}
function upd(){if(!open||!$('v-3d').classList.contains('on'))return;try{if(typeof mimic==='function')mimic()}catch(e){}const m=$('mimic');const sv=m&&(m.querySelector('.vmstage svg')||m.querySelector('svg'));if(sv)$('k3dMnS').innerHTML=sv.outerHTML}
function set(o){open=o;b.classList.toggle('on',o);p.classList.toggle('on',o);if(SC()&&SC().setBadges)SC().setBadges(o);if(o){build();upd();timer=setInterval(upd,1500)}else{clearInterval(timer);timer=null}}
b.addEventListener('click',()=>set(!open));$('k3dMnX').addEventListener('click',()=>set(false));$('k3dMnZ').addEventListener('click',()=>p.classList.toggle('big'));
})();
